version: '3.8'

services:
  tefas-app:
    build: .
    image: tefas-takip
    container_name: tefas-app
    ports:
      - "8080:80"
    volumes:
      - /Users/mehmet/Desktop/tefas_veriler:/app/data
    restart: unless-stopped
